# Generated by Django 3.0 on 2020-05-31 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='book',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='game.Book'),
            preserve_default=False,
        ),
    ]
