# Generated by Django 3.0 on 2020-06-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='right',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
