# Generated by Django 3.0 on 2020-06-04 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20200602_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='correct',
        ),
        migrations.AlterField(
            model_name='question',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='game.Book'),
        ),
    ]
