# Generated by Django 3.0 on 2020-06-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20200604_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='right',
        ),
        migrations.AddField(
            model_name='choice',
            name='correct',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
