# Generated by Django 3.0.7 on 2020-06-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_answer_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.IntegerField(choices=[(2, 'EASY'), (4, 'REGULAR'), (6, 'HARD')], default=2),
            preserve_default=False,
        ),
    ]
